---
version: '2'
services:

  sirjenkins:
    container_name: sirjenkins
    build: .
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      - HOSTNAME=jenkins.local
      - BUILD_ENV=local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./home/init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./home/workspace:/var/jenkins_home/workspace
      - ./jenkins_jobs:/etc/jenkins_jobs
      - ./home/setup.yml:/usr/share/jenkins/setup.yml
      - ../sirjenkins-ci:/sirjenkins-ci
